//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orders.Domain.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public System.Guid UUID { get; set; }
        public int UserID { get; set; }
        public int OrderState { get; set; }
        public string ShippingAddress { get; set; }
        public string Items { get; set; }
        public bool IsDeleted { get; set; }
    }
}
